const strings = {
    logout: 'logout',
    appName: 'OpenAHP',
    welcome: 'Bienvenido a OpenAHP ',
    nextstep: 'Pulsa sobre el engrane para ir a problemas',
    //problem table
    new: 'Crear nuevo problema',
    name: 'Nombre del Problema',
    deleteConfirm: 'Confirmar eliminación?',
    confirm: 'Aceptar',
    //editor
    comparison: 'Comparación',
    alternatives: 'Alternativas',
    pairwise: 'Por pares',
    gPairwise: 'Grafica por pares',
    verbal: 'Verbal',
    linear: 'Fundamental',
    balanced: 'Balanceada',
    scale: 'Escala',
    newAlternative: 'Añadir Alternativa',
    newCriteria: 'Nuevo criterio',
    saved: 'Guardado',
    errorRepeat: 'Error: Criterio o alternativa repetida',
    //noResults: 'Sin Resultados',
    //stepper
    data: 'Datos del Problema',
    params: 'Parámetros de Resolución',
    results: 'Resultados',
    probAnalisis: 'Análisis Probabilístico',
    analisis: 'Análisis de Sensibilidad',
    solve: 'Resolver',
    //List
    problem: 'Problema',
    objetive: 'Objetivo',
    autor: 'Autor',
    lastEdition: 'Ultima edición',
    lastResolution: 'Ultima resolución',
    noResults: 'Sin Resultados',
    //criteria tree
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    acept: 'Aceptar',
    cancel: 'Cancelar',
    criteria: 'Criterios',
    subCriteria: 'Subcriterio',
    addCriteria: 'Añadir criterio',
    addSubcriteria: 'Añadir Subcriterio',
    // verval pairwise
    equal:'Igual',
    moderate: 'Moderada',
    strong: 'Mucha',
    vStrong: 'Demasiada',
    extreme: 'Extrema',
    //sliders
    sliderTextImp: 'Comparar la relativa importancia respecto a:',
    sliderTextPref: 'Comparar la relativa preferencia respecto a:',
    //params
    consistency: 'Consistencia',
    error: 'Error',
    priority: 'Prioridad',
    cIndex: 'Índice de consistencia',
    cRatio: 'Razón de consistencia',
    cDet: 'Índice de determinantes',
    cIndexG: 'Índice de consistencia geométrico',
    errDes: 'Desviación cuadrática' ,
    errPri: 'Violaciones de prioridades',
    priVec: 'Vector propio',
    priMean: 'Media Geométrica',
    pricol: 'Columna normalizada',
    methods: 'Métodos',
    inconsistency: 'Inconsistencia',
    rank: 'Desempeños',
    weights: 'Pesos',
    random: 'Generador aleatorio ',
    simple: 'Simple',
    gamma: 'Gamma' ,
    pScale: 'Parámetro de escala',
    preserveRank: 'Preservar Orden',
    rankReversal: 'Rank Reversals',
    //result
    downloadResults: 'Descargar resultados',
    //probabilistic
    rankings: 'Rankings',
    calculate: 'Calcular',
    //analisis
    original: 'Resultado original',
    modified: 'Resultado modificado',

}
export default strings